#Requires -PSEdition Core
#Requires -Version 7

param(
    # NuGet Version Generated by GitVersion
    [Parameter(Mandatory = $true)]
    [ValidateNotNullOrEmpty()]
    [ValidatePattern('[0-9]+\.[0-9]+\.[0-9]+')]
    [string]
    $NuGetVersion,

    # Assembly Version Generated by GitVersion
    [Parameter(Mandatory = $true)]
    [ValidateNotNullOrEmpty()]
    [ValidatePattern('[0-9]+\.[0-9]+\.[0-9]+')]
    [string]
    $AssemblyVersion,

    # SHA-1 Git Commit hash
    [Parameter(Mandatory = $true)]
    [ValidateNotNullOrEmpty()]
    [string]
    $Sha
)

$packProjects = @(
    '.\OpenAISharp.Client\OpenAISharp.Client.csproj'
    '.\OpenAISharp.Completion\OpenAISharp.Completion.csproj'
    '.\OpenAISharp.Edit\OpenAISharp.Edit.csproj'
    '.\OpenAISharp.Embedding\OpenAISharp.Embedding.csproj'
    '.\OpenAISharp.File\OpenAISharp.File.csproj'
    '.\OpenAISharp.FineTune\OpenAISharp.FineTune.csproj'
    '.\OpenAISharp.Image\OpenAISharp.Image.csproj'
    '.\OpenAISharp.Model\OpenAISharp.Model.csproj'
    '.\OpenAISharp.Moderation\OpenAISharp.Moderation.csproj'
    '.\OpenAISharp.Utilities\OpenAISharp.Utilities.csproj'
)
$packOptions = "--output .\artifacts --configuration Release --no-restore --nologo -property:PackageVersion=${NuGetVersion} -property:AssemblyVersion=${AssemblyVersion} -property:FileVersion=${AssemblyVersion} -property:InformationalVersion=${Sha}"
Invoke-Expression -Command "dotnet pack .\OpenAISharp\OpenAISharp.csproj ${packOptions}"
foreach ($project in $packProjects) {
    Invoke-Expression "dotnet pack ${project} ${packOptions}"
}