name: dotnet package

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

jobs:
  build:

    runs-on: windows-2022
    strategy:
      matrix:
        dotnet-version: ['5.0.x', '6.0.x', '7.0.x' ]

    steps:
      # fetch-depth: 0 required for gitversion to work
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Install dependencies
        run: dotnet restore

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.10.2
        with:
          versionSpec: '5.x'

      - name: Determine Version
        uses: gittools/actions/gitversion/execute@v0.10.2
        id: gitversion
        with:
          useConfigFile: true

      - run: |
          echo "assemblySemFileVer: ${{ steps.gitversion.outputs.assemblySemFileVer }}"
          echo "Sha: ${{ steps.gitversion.outputs.Sha }}"
          echo "NuGetVersionV2: ${{ steps.gitversion.outputs.NuGetVersionV2 }}"

      - name: Build
        run: dotnet build --configuration Release --no-restore -p:AssemblyVersion=${{ steps.gitversion.outputs.assemblySemFileVer }} -p:FileVersion=${{ steps.gitversion.outputs.assemblySemFileVer }} -p:InformationalVersion=${{ steps.gitversion.outputs.Sha }}

      - name: Test
        run: dotnet test ./Tests/OpenAISharp.UnitTests/OpenAISharp.UnitTests.csproj --no-restore --verbosity normal

      - name: Package
        run: dotnet pack .\OpenAISharp\OpenAISharp.csproj --configuration Release --no-restore -p:PackageVersion=${{ steps.gitversion.outputs.NuGetVersionV2 }}

      - name: GitHub Tag
        if: github.ref == 'refs/heads/main'
        uses: mathieudutour/github-tag-action@v6.1
        with:
          custom_tag: ${{ steps.gitversion.outputs.NuGetVersionV2 }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
