name: dotnet package

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: windows-2022
    strategy:
      matrix:
        dotnet-version: ["5.0.x", "6.0.x", "7.0.x"]

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test ./Tests/OpenAISharp.UnitTests/OpenAISharp.UnitTests.csproj --no-restore --verbosity normal

      - name: Package
        run: dotnet pack .\OpenAISharp\OpenAISharp.csproj --configuration Release --no-restore

  package:
    runs-on: windows-2022
    needs: build
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: write

    steps:
      # fetch-depth: 0 required for gitversion to work
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET Core SDK 7.0.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.0.x"

      - name: Install dependencies
        run: dotnet restore

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.10.2
        with:
          versionSpec: "5.x"

      - name: Determine Version
        uses: gittools/actions/gitversion/execute@v0.10.2
        id: gitversion
        with:
          useConfigFile: true

      - name: GitVersion Information
        run: |
          echo "assemblySemFileVer: ${{ steps.gitversion.outputs.assemblySemFileVer }}"
          echo "Sha: ${{ steps.gitversion.outputs.Sha }}"
          echo "NuGetVersionV2: ${{ steps.gitversion.outputs.NuGetVersionV2 }}"
        shell: pwsh

      - name: Package
        run: |
          .\pack.ps1 -NuGetVersion ${{ steps.gitversion.outputs.NuGetVersionV2 }} -AssemblyVersion ${{ steps.gitversion.outputs.assemblySemFileVer }} -Sha ${{ steps.gitversion.outputs.Sha }}
        shell: pwsh

      - name: Publish
        run: |
          dotnet nuget push .\artifacts\*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_ORG_API_TOKEN }} --skip-duplicate
        shell: pwsh

      - name: GitHub Tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          custom_tag: ${{ steps.gitversion.outputs.NuGetVersionV2 }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
